version: '3.4'

services:
  vitereacttypescriptstarter:
    image: vitereacttypescriptstarter
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3001:3001
